modLoader = "javafml"
loaderVersion = "*"
license = "LGPLv3"
issueTrackerURL="https://JavaJumper/ImagineBook/issues"

[[mods]]
modId = "imaginebook"
version = "${version}"
displayName = "${name}"
authors = "JavaJumper"
description = ""
logoFile = "assets/imaginebook/icon.png"
logoBlur = false

[[mixins]]
config = "imaginebook-common.mixins.json"

[[mixins]]
config = "imaginebook-neoforge.mixins.json"